image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build MJX
    init: |
      git submodule update --init --recursive
      mkdir -p build && cd build
      cmake .. -DMJX_BUILD_PYTHON=ON -DMJX_BUILD_GRPC=ON -DMJX_BUILD_BOOST=OFF
      make -j$(nproc)
    command: |
      pip install .
