image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      git clone --recursive https://github.com/mjx-project/mjx.git
      cd mjx
      mkdir -p build && cd build
      cmake .. -DMJX_BUILD_PYTHON=ON -DMJX_BUILD_GRPC=ON -DMJX_BUILD_BOOST=OFF
      make -j$(nproc)
      pip install .
    command: |
      echo "MJX setup complete. You can now use Python and mjx."
